### ISSUE TITLE
一级标题前面会出现#符号

### ISSUE THREAD

**Issue by zfiber** [ITJoker233/Gridea-theme-Chic#15]
您好，我现在在用chic主题，现在发现markdown下一级标题的文字渲染后在文字前面会出现# ，四级标题前面会出现* ，这个是设置成这样的吗？在其他主题下应#或者* 是不会出现的。

**Comment by ITJoker233** [comment]
新版本会修复
XD

**Comment by ITJoker233** [comment]
已经修复

**Comment by zfiber** [comment]
谢谢，麻烦了！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ITJoker"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月1日(星期天) 晚上8:01
收件人:&nbsp;"ITJoker233/Gridea-theme-Chic"<Gridea-theme-Chic@noreply.github.com&gt;;
抄送:&nbsp;"492435471"<492435471@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ITJoker233/Gridea-theme-Chic] 一级标题前面会出现#符号 (#15)




已经修复

**Comment by zfiber** [comment]
CDN已经更新好了，一二级标题前面#已经没有了，三四级标题前还有符号“|”和“*”，等下次更新的时候可以一并修复下。

**Comment by ITJoker233** [comment]
已经修复....
