### ISSUE TITLE
能否添加自定义CDN功能

### ISSUE THREAD

**Issue by zhao-v** [ITJoker233/Gridea-theme-Chic#17]
在Gridea里可以直接手动选择CDN服务，或者添加自己的CDN服务。或者做俩个版本，一个是提供CDN服务的，一个是不含CDN服务的。目前是JSdeliver提供CDN服务。
![image](https://user-images.githubusercontent.com/59338524/76510437-9074e380-648c-11ea-9db7-aeb48925669a.png)

**Comment by ITJoker233** [comment]
可，迟点更新

**Comment by zhao-v** [comment]
好的，多谢大佬，大佬加油，今年确实不好找工作，尤其又赶上新冠肺炎。

**Comment by ITJoker233** [comment]
是啊

**Comment by angleHan** [comment]
请问现在添加CDN了吗

**Comment by ITJoker233** [comment]
> 请问现在添加CDN了吗

还没

**Comment by ITJoker233** [comment]
已经添加
