### ISSUE TITLE
黑夜模式代码块显示突兀

### ISSUE THREAD

**Issue by iamg7s** [ITJoker233/Gridea-theme-Chic#18]
在黑夜模式中，代码块显示很奇怪😂，希望大大有空能够解决一哈

**Comment by ITJoker233** [comment]
有截图么？

**Comment by iamg7s** [comment]
<img width="827" alt="1" src="https://user-images.githubusercontent.com/27910745/77159148-c561e580-6adf-11ea-814c-7455eb45154a.png">
<img width="716" alt="ligth" src="https://user-images.githubusercontent.com/27910745/77159181-d4489800-6adf-11ea-97e0-3a50ccaecf0d.png">
 黑夜模式看着好别扭，也不清楚是不是我设置的原因😂

**Comment by ITJoker233** [comment]
你重新弄下 prism.js的配色 XD
