### ISSUE TITLE
添加posts无效

### ISSUE THREAD

**Issue by DasKerr** [ITJoker233/Gridea-theme-Chic#2]
默认没有文章页，添加posts链接后，找不到页面

**Comment by ITJoker233** [comment]
应该不会的吧....
你把相关配置的截图发下，给我看看。（截图内容有Gridea的菜单配置，主题目录下的templates文件夹的内容）
可能是你配置的问题...

**Comment by ITJoker233** [comment]
应该不会的吧....
你把相关配置的截图发下，给我看看。（截图内容有Gridea的菜单配置，主题目录下的templates文件夹的内容）
可能是你配置的问题...

**Comment by DasKerr** [comment]
是我配置的问题，解决了，谢谢！

**Comment by DasKerr** [comment]
> 应该不会的吧....
> 你把相关配置的截图发下，给我看看。（截图内容有Gridea的菜单配置，主题目录下的templates文件夹的内容）
> 可能是你配置的问题...

是我配置的问题，解决了，谢谢！
