### ISSUE TITLE
希望像notes主题一样，在文章内容顶部可以查看封面图

### ISSUE THREAD

**Issue by YueqingSheng** [ITJoker233/Gridea-theme-Chic#20]
封面图本来就显示不全，希望能像notes主题一样，在顶部自动显示，会很好看的。
![test](https://user-images.githubusercontent.com/46506009/77510192-97b0cf80-6e44-11ea-8742-24dce607cfa2.jpg)

**Comment by ITJoker233** [comment]
好的，到时候更新

**Comment by YueqingSheng** [comment]
谢谢

**Comment by ITJoker233** [comment]
我会更新的，最近因为学业。hhh 赞助已收到,谢谢 XD

**Comment by YueqingSheng** [comment]
没事，不急的，学业为主。慢慢来 :>

**Comment by ITJoker233** [comment]
> 
> 
> 没事，不急的，学业为主。慢慢来 :>
最近忙着论文，还有一堆破事 XD

**Comment by YueqingSheng** [comment]
人艰不催，哈哈，慢慢来就好

**Comment by ITJoker233** [comment]
> 
> 
> 人艰不催，哈哈，慢慢来就好

XD
