### ISSUE TITLE
请问如何添加highlight.js的自定义样式

### ISSUE THREAD

**Issue by NCDWLQ** [ITJoker233/Gridea-theme-Chic#23]
我已经修改了head.ejs
增加以下代码，引入highlight.js的atom样式
```xml
<link rel="stylesheet" href="//cdn.jsdelivr.net/gh/highlightjs/cdn-release//build/styles/atom-one-dark.min.css">
```
已经成功加载，但是没有生效
样式仍然是原来的
![image.png](https://i.loli.net/2020/04/23/UwfJtLHnkdTaNPM.png)

**Comment by ITJoker233** [comment]
我内置高亮的了，所以你这个添加了无效
