### ISSUE TITLE
能否像 NexT 主题那样，增加文章css样式自定义功能？

### ISSUE THREAD

**Issue by yangfanbit** [ITJoker233/Gridea-theme-Chic#24]
更易修改，尤其对新手来说。

**Comment by ITJoker233** [comment]
具体怎么样的？XD

**Comment by yangfanbit** [comment]
类似这样
![](https://i.loli.net/2020/04/24/vDpfdxQAwWFmyqH.png)
（￣▽￣#）

**Comment by ITJoker233** [comment]
这种你在底部信息去添加也是一个效果的，只不过需要自己添加<style>你要添加的css</style>
![image](https://user-images.githubusercontent.com/39162691/107629661-6845c400-6c9d-11eb-80bc-fed4203f6530.png)
