### ISSUE TITLE
建议增加百度统计

### ISSUE THREAD

**Issue by UserUnknownX** [ITJoker233/Gridea-theme-Chic#28]
RT

可能体验更佳吧QwQ

**Comment by ITJoker233** [comment]
> RT
> 
> 可能体验更佳吧QwQ

能给个相关的link吗，我到时候看看

**Comment by UserUnknownX** [comment]
> > RT
> > 可能体验更佳吧QwQ
> 
> 能给个相关的link吗，我到时候看看

回复不周，>_<快期末了有点忙

[百度统计官网](https://tongji.baidu.com/)

[Gridea-theme-next制作者的博客集成了](https://tongji.baidu.com/)

**Comment by UserUnknownX** [comment]
> > RT
> > 可能体验更佳吧QwQ
> 
> 能给个相关的link吗，我到时候看看

我现在在尝试PR一下(最晚咕到7月中吧XD

**Comment by UserUnknownX** [comment]
> > > RT
> > > 可能体验更佳吧QwQ
> > 
> > 
> > 能给个相关的link吗，我到时候看看
> 
> 回复不周，>_<快期末了有点忙
> 
> [百度统计官网](https://tongji.baidu.com/)
> 
> [Gridea-theme-next制作者的博客集成了(有声警告](https://tongji.baidu.com/)

PR了XD

好像search.ejs的'include'部分没加.ejs报错(顺便加了个后缀

百度统计部分应该没问题，有问题就麻烦您帮忙改一下吧[>_<']
