### ISSUE TITLE
大佬你好，chic如何显示首页背景图

### ISSUE THREAD

**Issue by samondlee** [ITJoker233/Gridea-theme-Chic#29]
如果可以增加 首页 背景图 或者背景图随机轮播就好了

**Comment by ITJoker233** [comment]
> 如果可以增加 首页 背景图 或者背景图随机轮播就好了

更改首页背景么？emmmm看情况增加

**Comment by samondlee** [comment]
> > 如果可以增加 首页 背景图 或者背景图随机轮播就好了
> 
> 更改首页背景么？emmmm看情况增加

对的，https://github.com/xbclub/Hexo-theme-sakura 感觉这个背景图添加方式及效果可以参考一下。

**Comment by ITJoker233** [comment]
到时候增加个独立开关吧~

**Comment by ITJoker233** [comment]
不打算添加先，后面试试，我目前修复一些东西要大改东西
