### ISSUE TITLE
点击目录，无法跳转至指定位置

### ISSUE THREAD

**Issue by leichen2552** [ITJoker233/Gridea-theme-Chic#3]
https://leichen2552.github.io/post/hui-gu-4bu-er-lei-xing-he-yin-yong/
有目录，您可以点击看看。
还有黑暗模式下，代码的背景白色会占据右边目录的背景色，看上去很不协调。
我觉得界面还可以优化，比如目录可以更加靠右一些。

**Comment by ITJoker233** [comment]
我看看，我知道了，XD，大概知道什么原因了，目录的无法点击，试着下个版本更新。代码的背景白色会占据右边目录的背景色，这个我这里看不见....2333你用的是什么浏览器，我的火狐

**Comment by ITJoker233** [comment]
> 
> 
> https://leichen2552.github.io/post/hui-gu-4bu-er-lei-xing-he-yin-yong/
> 有目录，您可以点击看看。
> 还有黑暗模式下，代码的背景白色会占据右边目录的背景色，看上去很不协调。
> 我觉得界面还可以优化，比如目录可以更加靠右一些。

你把音乐插件关了就行。我大概排查到什么原因了

**Comment by leichen2552** [comment]
我用的是360极速浏览器，我说的代码的背景白色会占据右边目录的背景色是在黑暗模式下。因为在黑暗模式下，代码的背景还是白色太宽，会占据目录的暗黑背景。

**Comment by leichen2552** [comment]
哥们儿，我一直在用这个主题，加个微信聊聊，Asura_FE，茕茕孑立，加我！



在 2020-01-30 10:11:43，"ITJoker" <notifications@github.com> 写道：

我看看，我知道了，XD，大概知道什么原因了，目录的无法点击，试着下个版本更新。代码的背景白色会占据右边目录的背景色，这个我这里看不见....2333你用的是什么浏览器，我的火狐

**Comment by ITJoker233** [comment]
你用Chrome或者火狐浏览器就行

**Comment by ITJoker233** [comment]
我大概找到原因了，1.6.5的时候更新看看
