### ISSUE TITLE
评论区会错位，不知道怎么解决

### ISSUE THREAD

**Issue by Tony1026** [ITJoker233/Gridea-theme-Chic#33]
用valine评论，PC端上评论区会左偏，手机端似乎没有这个问题，不知道要怎么解决。。

**Comment by ITJoker233** [comment]
我看看到时候，因为是别人pr过来的，我还没调试...

**Comment by ITJoker233** [comment]
> 用valine评论，PC端上评论区会左偏，手机端似乎没有这个问题，不知道要怎么解决。。

具体截图有么？给我看看，我好定位，最好把分辨率、浏览器啥的也发下

**Comment by Tony1026** [comment]
[https://i.loli.net/2020/07/07/rj3gTLSckKDwOAX.png](url)
Google Chrome | 83.0.4103.116 (正式版本) （64 位）
Windows 10 OS Version 2004 (Build 19041.329)
1920x1080
