### ISSUE TITLE
Render custom page error

### ISSUE THREAD

**Issue by Tony1026** [ITJoker233/Gridea-theme-Chic#34]
Gridea/themes/Chic/templates/search.ejs

```javascript
<head>
<%- include('./include/head.ejs', { siteTitle: themeConfig.siteName }) %>
<script src="//cdn.jsdelivr.net/gh/tangkaichuan/gridea-search/lib/fuse.js"></script>
<script src="//cdn.jsdelivr.net/gh/tangkaichuan/gridea-search/lib/ejs.min.js"></script>
<script src="//cdn.jsdelivr.net/gh/tangkaichuan/gridea-search/lib/gridea-search.min.js"></script>
```

Missing catch or finally after try in Gridea\themes\Chic\templates\include\head.ejs while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass async: true as an option.

求解决

**Comment by ITJoker233** [comment]
已经修复了XD 那部分代码不是我写的 哈哈哈

**Comment by ITJoker233** [comment]
> Gridea/themes/Chic/templates/search.ejs
> 
> ```js
> <head>
> <%- include('./include/head.ejs', { siteTitle: themeConfig.siteName }) %>
> <script src="//cdn.jsdelivr.net/gh/tangkaichuan/gridea-search/lib/fuse.js"></script>
> <script src="//cdn.jsdelivr.net/gh/tangkaichuan/gridea-search/lib/ejs.min.js"></script>
> <script src="//cdn.jsdelivr.net/gh/tangkaichuan/gridea-search/lib/gridea-search.min.js"></script>
> ```
> 
> Missing catch or finally after try in Gridea\themes\Chic\templates\include\head.ejs while compiling ejs
> 
> If the above error is not helpful, you may want to try EJS-Lint:
> https://github.com/RyanZim/EJS-Lint
> Or, if you meant to create an async function, pass async: true as an option.
> 
> 求解决

重新pull 一下就行
```git pull origin master```
