### ISSUE TITLE
你好，那个搜索框是不是有问题，我触碰上去会动，

### ISSUE THREAD

**Issue by tangxuchao** [ITJoker233/Gridea-theme-Chic#35]
[https://external-30160.picsz.qpic.cn/c275c5ef7f4978d3f51df2b53c4d4dc5](url)

**Comment by ITJoker233** [comment]
就是会动的，XD 我后期有些要重新设计下的

**Comment by tangxuchao** [comment]
好的， 就说感觉很别扭
