### ISSUE TITLE
如何使用天气插件

### ISSUE THREAD

**Issue by YuZhangWang** [ITJoker233/Gridea-theme-Chic#36]
看到更新加入了天气插件，但是readme里没有写进去，所以想询问下

**Comment by ITJoker233** [comment]
自定义设置里

**Comment by YuZhangWang** [comment]
> 自定义设置里

我看到这个选项并且勾选了，但是在我的博客上，找不到天气显示，博客链接https://yuzhangwang.github.io/

**Comment by ITJoker233** [comment]
天气接口更新了，我试试修复下

**Comment by YuZhangWang** [comment]
> 天气接口更新了，我试试修复下
好的，麻烦了
昨天我在测试中发现，访问量插件，似乎也挂了，现在阅读量处只有"-"符号，并未显示阅读数量
此外，我看到readme中看到了“支持Live 2d , 一言API,音乐播放器(支持手动导入歌单)....”这句介绍，我理解为支持歌单导入，不过在主题自定义设置Music插件的地方和音乐插件教程处都只看到了单首音乐导入方法。不知道音乐插件是本身不支持导入歌单还是歌单导入另有方法但是没有写？

**Comment by ITJoker233** [comment]
有些是可能挂了，我下个版本修复下
手动导入就是手动输入

**Comment by ITJoker233** [comment]
点+就可以了

**Comment by YuZhangWang** [comment]
> 有些是可能挂了，我下个版本修复下
> 手动导入就是手动输入

好的，理解介绍的意思了

**Comment by YuZhangWang** [comment]
> 点+就可以了

好的好的，没问题
