### ISSUE TITLE
建议在 posts 和 archives 页加入翻页功能

### ISSUE THREAD

**Issue by imzzy1201** [ITJoker233/Gridea-theme-Chic#37]
文章多了全放在一面页面就太长了点，Gridea 客户端也给了”每页文章数“和”每页归档数“的设置，所以希望每页只显示固定个数的文章并支持翻页

**Comment by ITJoker233** [comment]
归档页可以，posts页面不支持翻页

**Comment by ITJoker233** [comment]
文章列表gridea不支持的，是我自己加的，根据其中一位网友添加的，归档页的是支持翻页的
