### ISSUE TITLE
求大神帮忙解决

### ISSUE THREAD

**Issue by liranderan** [ITJoker233/Gridea-theme-Chic#50]
装了新版本之后,一直显示错误状态
<img width="1356" alt="截屏2020-10-06 下午12 14 48" src="https://user-images.githubusercontent.com/41143538/95249601-c7666a00-07cd-11eb-8db9-91d9a2541d43.png">

**Comment by ITJoker233** [comment]
?有图么

**Comment by liranderan** [comment]
> ?有图么

上面就是

**Comment by ITJoker233** [comment]
> > ?有图么
> 
> 上面就是

没看到啊
