### ISSUE TITLE
一直搜索中

### ISSUE THREAD

**Issue by radiumtall** [ITJoker233/Gridea-theme-Chic#51]
![image](https://user-images.githubusercontent.com/39807447/97771519-88cb9180-1b78-11eb-947a-582fd0db9e22.png)

请问为什么一直是搜索中呢

**Comment by ITJoker233** [comment]
> ![image](https://user-images.githubusercontent.com/39807447/97771519-88cb9180-1b78-11eb-947a-582fd0db9e22.png)
> 
> 请问为什么一直是搜索中呢

应该是没有搜索到

**Comment by hwtz** [comment]
现在还是这样！
