### ISSUE TITLE
文章评论框没有设置边界，在较低辨率下评论框错位

### ISSUE THREAD

**Issue by SoraKasvgano** [ITJoker233/Gridea-theme-Chic#52]
文章评论框没有设置边界，在较低辨率下评论框错位
![捕获](https://user-images.githubusercontent.com/8521327/102314780-f6f3d880-3fad-11eb-9422-d79c9b41c012.JPG)

**Comment by ITJoker233** [comment]
阿这，Valine的那个我到时候看看 XD

**Comment by zjs1224522500** [comment]
这个有解决方案吗？用最新的代码好像还是这样的？
