### ISSUE TITLE
能否增加个文章访问需要密码的功能？

### ISSUE THREAD

**Issue by Lulululx** [ITJoker233/Gridea-theme-Chic#53]
之前一直用ty，里面有个主题有文章访问需要密码的功能感觉挺好的，不知道能不能在这个主题上也增加？（小白不太清楚）

**Comment by kain-hao** [comment]
用 [txtshare.org](https://txtshare.org) 然后iframe嵌入进去... 试试(

**Comment by ITJoker233** [comment]
我看看吧，再说...

**Comment by ITJoker233** [comment]
> 用 [txtshare.org](https://txtshare.org) 然后iframe嵌入进去... 试试(

这个官方没有提供api，不好搞，如果iframe的话，可能会有一堆问题....

**Comment by kain-hao** [comment]
> 
> 
> > 用 [txtshare.org](https://txtshare.org) 然后iframe嵌入进去... 试试(
> 
> 这个官方没有提供api，不好搞，如果iframe的话，可能会有一堆问题....

~~但是我就是站长啊.jpg~~
右上角有个嵌入至少能用(?

**Comment by ITJoker233** [comment]
但是iframe的话，你写文章的时候就可以自己设置了，我主题里咋兼容啊
