### ISSUE TITLE
搜索

### ISSUE THREAD

**Issue by hwtz** [ITJoker233/Gridea-theme-Chic#54]
有没有办法将搜索关掉？

**Comment by ITJoker233** [comment]
> 有没有办法将搜索关掉？

在主题——>自定义设置里

**Comment by hezhiming1995** [comment]
1.7.6.1版本，没有找到具体的关闭按钮，作者可以方便再提示指导一下吗？

**Comment by ITJoker233** [comment]
> 1.7.6.1版本，没有找到具体的关闭按钮，作者可以方便再提示指导一下吗？

指的是关闭搜索这个功能么？我记得是不支持的~ 已经很久没看过这部分代码了。

**Comment by ITJoker233** [comment]
> 1.7.6.1版本，没有找到具体的关闭按钮，作者可以方便再提示指导一下吗？

可能是因为gridea更新了缘故？或者操作不对导致的
