### ISSUE TITLE
右侧目录，一级目录和二级目录之间的水平间距可以短一些吗，15.6寸笔记本显示难看

### ISSUE THREAD

**Issue by leichen2552** [ITJoker233/Gridea-theme-Chic#9]
以及连续的各级目录之间的水平间距都短一些，例如一级目录与二级目录之间，二级目录与三级目录之间等等，我觉得大概一个字的宽度刚刚好。
[https://leichen2552.github.io/post/rtos_from_zero_to_one/](url)

**Comment by ITJoker233** [comment]
我到时候做做适配，这个我在我笔记本上看见了😂你的具体分辨率多少？
